name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run python -m pytest .
